### ISSUE TITLE
Optionset enums blow up if there are special characters in the optionset text

### ISSUE THREAD

**Issue by kheiman61** [pederwagner/XrmSdkWebAPI#1]
In the generated files, optionset enums throw errors when creating javascript from typescript files

Example: On contact/account the optionset for PaymentTermsCodeValues prevents .js from being created until you fix: (for example in the generated file XrmSdk.Account.ts) 

```
export var PaymentTermsCodeValues: any = {
    Net_30: 1,
    2%_10_Net_30:` 2,
    Net_45: 3,
    Net_60: 4
```

to be something like this instead:

```
export var PaymentTermsCodeValues: any = {
    Net_30: 1,
    TwoPct_10_Net_30: 2,
    Net_45: 3,
    Net_60: 4
```

**Comment by pederwagner** [comment]
This is fixed using a whitelist regex pattern, that removes all characters except the allowed ones
