### ISSUE TITLE
Does not appear to handle lookup values properly

### ISSUE THREAD

**Issue by kheiman61** [pederwagner/XrmSdkWebAPI#2]
I can 'manually' tweak lookup values (such as 'parentcustomerid') with something like:

```
var contactManual = {};
contactManual["parentcustomerid_account@odata.bind"] = "/accounts(" + accountId + ')';

//test update 
XrmSdk.WebAPI.update(XrmSdk.Contact.EntityDataSetName, primaryContactId, contactManual, null, false);
```

but the default behavior of 'update' doesn't appear to work with the generated files. Would be nice for the generated files to handle lookup attributes.

**Comment by pederwagner** [comment]
The generated file now has a set function for each navigation property, that can be used to accomplish what you want. Also, all the generated data now comes from the odata metadata document (XML) and not the metadata service (SOAP) / SDK.
